### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by jm-riley** [G07Watch/CoffeeWithAliens#1]
### users
- [x] booleans such as `is_host` should have default value of false

### coffee times
- [ ] consider storing `start_time` as type string or datetime

### hosts
- do we need a separate hosts table or can all of this info be stored on the users table?

Looks great!

**Comment by G07Watch** [comment]
**users**

 * updated boolean data types to have default : false

**coffee times**

 * start_times may be refactored to a datetime, depending on whether the integer or datetime calculations are more expensive

**hosts**

 * host table was created to reduce bulk on users table and to make manipulation of host data easier to manage
