### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by jm-riley** [G07Watch/CoffeeWithAliens#4]
Looking great, Garvin!

Couple of small issues:
- [x] clear errors when switching between login / signup forms
- [x] add a `cursor: pointer` hover effect to your `Sign Out` button
- [x] can get rid of `Error:` when listing error messages

**Comment by G07Watch** [comment]
* added `cleanErrors` action for clearing errors on `componentWillUnmount`
 * adds `cursor:pointer` hover effect to `Sign Out` button
 * removed `Error:` header for error message listing
